// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKTDfOp9MTaPw-YBXpkJ2EHGlEZGgJGFA',
    appId: '1:624256671364:web:c9c55a5dc451db3cdaecd1',
    messagingSenderId: '624256671364',
    projectId: 'aya-project-8bc95',
    authDomain: 'aya-project-8bc95.firebaseapp.com',
    storageBucket: 'aya-project-8bc95.appspot.com',
    measurementId: 'G-RXH0YKCZRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9rP3qRUmMNtMsqRI8Saj_C_RF1fUGXWA',
    appId: '1:624256671364:android:3bed6773810b7b4bdaecd1',
    messagingSenderId: '624256671364',
    projectId: 'aya-project-8bc95',
    storageBucket: 'aya-project-8bc95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAojq0nPZX0nC_T-cfZUAjOnkoyXi6w16Q',
    appId: '1:624256671364:ios:c465c328f42bb702daecd1',
    messagingSenderId: '624256671364',
    projectId: 'aya-project-8bc95',
    storageBucket: 'aya-project-8bc95.appspot.com',
    iosClientId: '624256671364-ak05t07748mgkbc0am5c7jlhioufhbbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.aya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAojq0nPZX0nC_T-cfZUAjOnkoyXi6w16Q',
    appId: '1:624256671364:ios:c465c328f42bb702daecd1',
    messagingSenderId: '624256671364',
    projectId: 'aya-project-8bc95',
    storageBucket: 'aya-project-8bc95.appspot.com',
    iosClientId: '624256671364-ak05t07748mgkbc0am5c7jlhioufhbbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.aya',
  );
}
